NOTION_TOKEN = "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"           # Internal Integration Token z Notion
NOTION_DATABASE_ID = "216aaf4924e5802890f4f1235aa8ecc8?v=216aaf4924e580ab889f000c11e963f1"   # ID bazy „Sezon 1”
TIMEZONE = "Europe/Warsaw"
